<main id="connexion">
    <div id="en-tete"></div>
    <h1>Se connecter</h1>
    <p class="lightfont">En vous connectant, vous pourrez accéder à votre liste de recettes favorites et en ajouter de nouvelles. Si vous n'avez pas de compte, vous pouvez en créer un gratuitement.</p>
    <a href="newUser.php">Créer un compte</a>  
    <form class="connect">
        <input class="my-5" type="text" name="email" id="email" aria-describedby="emailHelp" placeholder="Adresse email">
        <input class="my-5" type="password" name="mdp" id="password" placeholder="Mot de passe"><br>
        <input type="submit" name="connexion" value="Connexion">
    </form>
    <div class="failed"></div>
</main>
