<main id="recipe" class="row">
    <div id="en-tete" style="background-image:url(<?= $recipe['imgSrcRecipe'] ?>)"></div>
    <h1><?= $recipe["recipeName"] ?></h1>
    <a href="recettesFav.php"><i class="far fa-heart mr-3"></i> Ajouter cette recette en favoris</a>
    <section class="d-flex justify-content-between flex-wrap">  
        <article class="ingredient col-12 col-lg-4 d-flex flex-column align-items-center">
            <h3><span class="text-uppercase">Ingrédients</span></h3>
            <div>
                <?= $recipe["ingredientRecipe"] ?>
            </div>
        </article>
        <article class="recipe col-12 col-lg-8">
            <?= $recipe["descriptionRecipe"] ?>
        </article>
    </section>
</main>    
