<!DOCTYPE html>
<html lang="fr">
<head>
    <link rel="shortcut icon" href="img/icons/favicon.ico" type="image/x-icon">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Smooth Maker</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat+Alternates:300" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css" />
</head>

<body id="layout">

    <header class="d-flex justify-content-between align-items-center">
        <a href="index.php"><img src="img/logo/logo.png" alt="Logo SmoothMaker"></a>
        <?php $userSession = new UserSession();
        if($userSession->isAuthenticated()): ?>
        <div class="infoUser d-flex flex-column">
            <p>Bonjour <strong><?= $userSession->getFullName() ?></strong> !</p>
            <a class="btn discover" href="logout.php">Déconnexion</a>  
        </div>
        <?php endif; ?>
        <nav class="nav navDesktop">
            <a class="nav-link font-weight-bold text-uppercase mx-4" href="index.php">Accueil</a>
            <a class="nav-link font-weight-bold text-uppercase mx-4" href="nosSmoothies.php">Smoothies</a>
            <a class="nav-link font-weight-bold text-uppercase mx-4" href="nosRecettes.php">Recettes</a>
            <a class="nav-link font-weight-bold text-uppercase mx-4" href="lebar.php">Le bar</a>
        </nav>
        <!-- Menu mobile caché -->
        <section class="mobileIndexMenu">
            <p class="menuMobile btn discover"><i class="fas fa-bars"></i> Menu</p>
            <nav class="navMobile" style="display:none">
                <a class="nav-link text-white text-uppercase mx-4" href="index.php">Accueil</a>
                <a class="nav-link text-white text-uppercase mx-4" href="nosSmoothies.php">Smoothies</a>
                <a class="nav-link text-white text-uppercase mx-4" href="nosRecettes.php">Recettes</a>
                <a class="nav-link text-white text-uppercase mx-4" href="lebar.php">Le bar</a>
            </nav>
        </section>
        <!-- ****************** -->
    </header>

    <?php include "$page.phtml" ?>
 
    <footer>
        <p>Partage ton smoothie sur les réseaux sociaux avec </p>
        <p>#Smooth Maker</p>
        <div>
            <a href="#"><img class="reseaux" src="img/icons/instagram.png" alt="Instagram"></a>
            <a href="#"><img class="reseaux" src="img/icons/facebook.png" alt="Facebook"></a>
        </div>
        <small>2018 © SmoothMaker Lyon - Mentios Légales - Contact</small>
    </footer>

</body>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" ></script>
    <script src="js/main.js"></script>
    <!-- <script type="text/javascript" src="js/helium.js" onload="helium.init()" async></script> -->
</html> 
