<main id="bar">
    <section id="en-tete" class="row">
        <div class="image col-6"></div>
        <div class="titre col-6 d-flex align-items-center">
            <h1>Le bar à Smoothie</h1>
        </div>
        <div class="texte">
            <p class="lightfont">Venez profiter de la terrasse ombragée. Nos smoothies peuvent être servis accompagnés de petites douceurs gourmandes. Nos smoothies sont bios et faits avec des produits de saison.</p>
        </div>
    </section>

    <!-- Nous trouvez -->
    <section id="findUs" class="row">
        <div class="title-text">
            <div class="title-findUs">
                <h2>Nous trouver</h2>
                <p class="lightfont">venez boire un coup smooth détente</p>
            </div>
            <div class="text-findUs">
                <p><i class="fas fa-map-maker-alt"></i>25, rue République</p>
                <p>69002 Lyon</p>
                <p> <i class="fas fa-phone"></i> 04 78 02 03</p>
                <p><i class="fas fa-envelope"></i> smooth@maker.fr</p>
            </div> 
        </div>
        <div class="frame">
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d11139.690931447602!2d4.899485299999999!3d45.732644349999994!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1546503954206" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>            
        </div>
        <div class="horaires title-findUs text-center">
            <h2>Nos Horaires</h2>
            <p class="lightfont">Lundi : 10h - 19h</p>
            <p class="lightfont">Mardi : fermé</p>
            <p class="lightfont">Mercredi : 10h - 20h</p>
            <p class="lightfont">Jeudi : 14h - 19h</p>
            <p class="lightfont">Vendredi : 10h - 21h</p>
            <p class="lightfont">Samedi : 10h - 21h</p>
            <p class="lightfont">Dimanche : fermé</p>
        </div>
    </section>   
    <section id='message'>
        <form>
            <h2>Nous écrire</h2>
            <input class="my-5" type="text" name="email" id="email" aria-describedby="emailHelp" placeholder="Adresse email">
            <textarea class="send-message my-5" type="text" name="message" id="message" placeholder="Message"></textarea>
            <input class="sendEmail" type="submit" name="connexion" value="Envoyer">
        </form>
        <div class="failed"></div>
    </section> 
</main>
